#include "dc_prob.h"
#include "lc_corr.h"

int PIPO64_OFFSET[8] = { -1, -1, -1, -1, -1, -1, -1, -1 };

PROB_t MAX_PROB; //non-one probability
PROB_t MIN_PROB; //non-zero probability
DP_I_O_PROB_t	DP_IOP[PIPO64_SBOX_CARDINALITY * PIPO64_SBOX_CARDINALITY];
DP_I_PROB_t		DP_IP_FO[PIPO64_SBOX_CARDINALITY][PIPO64_SBOX_CARDINALITY];
DP_O_PROB_t		DP_OP_FI[PIPO64_SBOX_CARDINALITY][PIPO64_SBOX_CARDINALITY];
SUB_CNT_t DP_NUM_IOP_NONZERO;
SUB_CNT_t DP_NUM_IOP_MAX;
SUB_CNT_t DP_NUM_IP_FO_NONZERO[PIPO64_SBOX_CARDINALITY];
SUB_CNT_t DP_NUM_IP_FO_MAX[PIPO64_SBOX_CARDINALITY];
SUB_CNT_t DP_NUM_OP_FI_NONZERO[PIPO64_SBOX_CARDINALITY];
SUB_CNT_t DP_NUM_OP_FI_MAX[PIPO64_SBOX_CARDINALITY];


CORR_t MAX_CORR; //non-one abs correlation
CORR_t MIN_CORR; //non-zero correlation
LC_I_O_CORR_t	LC_IOC[PIPO64_SBOX_CARDINALITY * PIPO64_SBOX_CARDINALITY];
LC_I_CORR_t		LC_IC_FO[PIPO64_SBOX_CARDINALITY][PIPO64_SBOX_CARDINALITY];
LC_O_CORR_t		LC_OC_FI[PIPO64_SBOX_CARDINALITY][PIPO64_SBOX_CARDINALITY];
SUB_CNT_t LC_NUM_IOC_NONZERO;
SUB_CNT_t LC_NUM_IOC_MAX;
SUB_CNT_t LC_NUM_IC_FO_NONZERO[PIPO64_SBOX_CARDINALITY];
SUB_CNT_t LC_NUM_IC_FO_MAX[PIPO64_SBOX_CARDINALITY];
SUB_CNT_t LC_NUM_OC_FI_NONZERO[PIPO64_SBOX_CARDINALITY];
SUB_CNT_t LC_NUM_OC_FI_MAX[PIPO64_SBOX_CARDINALITY];